theme: jekyll-theme-cayman
title: Calculator for Persistent Homology
description: An algebraic tool for topological pattern recognition in metric data sets.
show_downloads: true
github:
  zip_url: https://example.com/foo.zip
  tar_url: https://example.com/foo.tar.gz
