theme: jekyll-theme-cayman
markdown: kramdown
title: Calculator for Persistent Homology
description: An algebraic tool for topological pattern recognition in metric data sets.
show_downloads: true
github:
  zip_url: https://github.com/jmaerte/persistent_homology/zipball/master/
  tar_url: https://github.com/jmaerte/persistent_homology/tarball/master/
